### ISSUE TITLE
Handle case where text file cannot be encoded by CP1252 gracefully.

### ISSUE THREAD

**Issue by bohning** [bohning/usdb_syncer#101]
If the user has selected CP1252 output, but the text file contains symbols that cannot be converted to CP1252, the syncer crashes.

```
2023-02-26 23:03:50 [ERROR] Uncaught exception:
    Traceback (most recent call last):
      File "usdb_syncer\song_loader.py", line 159, in run
      File "usdb_syncer\song_loader.py", line 271, in _maybe_write_txt
      File "usdb_syncer\songtxt_init.py", line 61, in write_to_file
      File "encodings\cp1252.py", line 19, in encode
    UnicodeEncodeError: 'charmap' codec can't encode character '\u2032' in position 2232: character maps to <undefined>
```

**Comment by bohning** [comment]
Maybe the settings dialogue could be extended and if the user selects CP1252, he/she can decide how these cases should be handled (skip song/replace characters with ?/replace characters with unicode escape sequence/ask for each song/...).
