### ISSUE TITLE
Executable dependent on chrome

### ISSUE THREAD

**Issue by TheNailDev** [bohning/usdb_syncer#130]
Hi,
I wanted to try the new released build 0.0.1 for Windows.
Sadly, the application crashes on startup. It seems to me that it is related to Google Chrome not being installed on my Computer.
Here is the error message:

```
2023-05-04 20:03:47 [ERROR] Uncaught exception:
    Traceback (most recent call last):
      File "usdb_syncer\main.py", line 36, in <module>
      File "usdb_syncer\main.py", line 31, in cli_entry
      File "usdb_syncer\gui\mw.py", line 306, in main
      File "usdb_syncer\gui\mw.py", line 315, in _load_main_window
      File "usdb_syncer\song_list_fetcher.py", line 23, in get_all_song_data
      File "usdb_syncer\song_list_fetcher.py", line 49, in get_available_songs
      File "usdb_syncer\usdb_scraper.py", line 333, in get_usdb_available_songs
      File "usdb_syncer\usdb_scraper.py", line 231, in get_usdb_page
      File "usdb_syncer\usdb_scraper.py", line 222, in page
      File "usdb_syncer\usdb_scraper.py", line 78, in session
      File "usdb_syncer\usdb_scraper.py", line 64, in new_session_with_cookies
      File "usdb_syncer\settings.py", line 220, in cookies
      File "browser_cookie3\__init__.py", line 973, in chrome
      File "browser_cookie3\__init__.py", line 516, in __init__
      File "browser_cookie3\__init__.py", line 331, in __init__
      File "browser_cookie3\__init__.py", line 378, in __add_key_and_cookie_file
    browser_cookie3.BrowserCookieError: Failed to find Chrome cookie
[15584] Failed to execute script 'main' due to unhandled exception!
```

It would be nice, if the program could start, even if no chrome cookies could be found.

**Comment by bohning** [comment]
Thanks for the quick error report, this was a test release to see if everything builds okay in the CI. We'll fix the Chrome bug in the actual release. Stay tuned.
