### ISSUE TITLE
Cannot load library /tmp/_MEIUOOPug/PySide6/Qt/plugins/platforms/libqxcb.so

### ISSUE THREAD

**Issue by DerGitRob** [bohning/usdb_syncer#137]
Thanks for keeping up with this project, I'm excited to see how it will work and keep the usdb community alive.
Unfortunately, I got the mentioned error while executing the 0.1.0 release file on Debian sid:
"Cannot load library /tmp/_MEIUOOPug/PySide6/Qt/plugins/platforms/libqxcb.so"

**Comment by mjhalwa** [comment]
I think I can reproduce the Issue on Ubuntu 23.04. I get the following output

```
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, wayland, wayland-egl, vnc, vkkhrdisplay, offscreen, minimalegl, minimal, linuxfb, eglfs.

Aborted (core dumped)
```

with following steps:

## with the Release 0.1.0 for Linux

1. Download `USDB_Syncer-0.1.0-Linux`
2. Enable execution
    ``` sh
    chmod +x USDB_Syncer-0.1.0-Linux
    ```
3. Run `./USDB_Syncer-0.1.0-Linux` 

## with clone of `main` branch at e2f3991

with `python3` at version `3.11.2`

1. Install Prerequisites

    ``` sh
    apt install python3-venv
    ```

2. Setup

    ``` sh
    python3 -m venv venv
    source venv/bin/activate
    pip install --upgrade pip tox setuptools
    pip install -e '.[dev]'
    ```

3. Run `usdb_syncer`

**Comment by mjhalwa** [comment]
Looking up on Google I found https://forum.qt.io/topic/93247/qt-qpa-plugin-could-not-load-the-qt-platform-plugin-xcb-in-even-though-it-was-found?lang=en-US where they suggested to diagnose with `QT_DEBUG_PLUGINS=1`. I tried on both:

- release

  ```
  QT_DEBUG_PLUGINS="1" ./USDB_Syncer-0.1.0-Linux
  ```

- and clone

  ```
  QT_DEBUG_PLUGINS="1" usdb_syncer
  ```

and both returned the same, where the only difference was the path to pyside `platforms` directory, which is `/tmp/_MEIubOd8D/PySide6/Qt/plugins/platforms/` for the release. This is the full output of the clone:

```
qt.core.plugin.factoryloader: checking directory path "/home/ubuntu/git/usdb_syncer/venv/lib/python3.11/site-packages/PySide6/Qt/plugins/platforms" ...
qt.core.plugin.factoryloader: looking at "/home/ubuntu/git/usdb_syncer/venv/lib/python3.11/site-packages/PySide6/Qt/plugins/platforms/libqxcb.so"
qt.core.plugin.loader: Found metadata in lib /home/ubuntu/git/usdb_syncer/venv/lib/python3.11/site-packages/PySide6/Qt/plugins/platforms/libqxcb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "xcb"
        ]
    },
    "archlevel": 1,
    "className": "QXcbIntegrationPlugin",
    "debug": false,
    "version": 394496
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("xcb")
qt.core.plugin.factoryloader: looking at "/home/ubuntu/git/usdb_syncer/venv/lib/python3.11/site-packages/PySide6/Qt/plugins/platforms/libqwayland-generic.so"
qt.core.plugin.loader: Found metadata in lib /home/ubuntu/git/usdb_syncer/venv/lib/python3.11/site-packages/PySide6/Qt/plugins/platforms/libqwayland-generic.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "wayland"
        ]
    },
    "archlevel": 1,
    "className": "QWaylandIntegrationPlugin",
    "debug": false,
    "version": 394496
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("wayland")
qt.core.plugin.factoryloader: looking at "/home/ubuntu/git/usdb_syncer/venv/lib/python3.11/site-packages/PySide6/Qt/plugins/platforms/libqwayland-egl.so"
qt.core.plugin.loader: Found metadata in lib /home/ubuntu/git/usdb_syncer/venv/lib/python3.11/site-packages/PySide6/Qt/plugins/platforms/libqwayland-egl.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "wayland-egl"
        ]
    },
    "archlevel": 1,
    "className": "QWaylandEglPlatformIntegrationPlugin",
    "debug": false,
    "version": 394496
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("wayland-egl")
qt.core.plugin.factoryloader: looking at "/home/ubuntu/git/usdb_syncer/venv/lib/python3.11/site-packages/PySide6/Qt/plugins/platforms/libqvnc.so"
qt.core.plugin.loader: Found metadata in lib /home/ubuntu/git/usdb_syncer/venv/lib/python3.11/site-packages/PySide6/Qt/plugins/platforms/libqvnc.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "vnc"
        ]
    },
    "archlevel": 1,
    "className": "QVncIntegrationPlugin",
    "debug": false,
    "version": 394496
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("vnc")
qt.core.plugin.factoryloader: looking at "/home/ubuntu/git/usdb_syncer/venv/lib/python3.11/site-packages/PySide6/Qt/plugins/platforms/libqvkkhrdisplay.so"
qt.core.plugin.loader: Found metadata in lib /home/ubuntu/git/usdb_syncer/venv/lib/python3.11/site-packages/PySide6/Qt/plugins/platforms/libqvkkhrdisplay.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "vkkhrdisplay"
        ]
    },
    "archlevel": 1,
    "className": "QVkKhrDisplayIntegrationPlugin",
    "debug": false,
    "version": 394496
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("vkkhrdisplay")
qt.core.plugin.factoryloader: looking at "/home/ubuntu/git/usdb_syncer/venv/lib/python3.11/site-packages/PySide6/Qt/plugins/platforms/libqoffscreen.so"
qt.core.plugin.loader: Found metadata in lib /home/ubuntu/git/usdb_syncer/venv/lib/python3.11/site-packages/PySide6/Qt/plugins/platforms/libqoffscreen.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "offscreen"
        ]
    },
    "archlevel": 1,
    "className": "QOffscreenIntegrationPlugin",
    "debug": false,
    "version": 394496
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("offscreen")
qt.core.plugin.factoryloader: looking at "/home/ubuntu/git/usdb_syncer/venv/lib/python3.11/site-packages/PySide6/Qt/plugins/platforms/libqminimalegl.so"
qt.core.plugin.loader: Found metadata in lib /home/ubuntu/git/usdb_syncer/venv/lib/python3.11/site-packages/PySide6/Qt/plugins/platforms/libqminimalegl.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "minimalegl"
        ]
    },
    "archlevel": 1,
    "className": "QMinimalEglIntegrationPlugin",
    "debug": false,
    "version": 394496
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("minimalegl")
qt.core.plugin.factoryloader: looking at "/home/ubuntu/git/usdb_syncer/venv/lib/python3.11/site-packages/PySide6/Qt/plugins/platforms/libqminimal.so"
qt.core.plugin.loader: Found metadata in lib /home/ubuntu/git/usdb_syncer/venv/lib/python3.11/site-packages/PySide6/Qt/plugins/platforms/libqminimal.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "minimal"
        ]
    },
    "archlevel": 1,
    "className": "QMinimalIntegrationPlugin",
    "debug": false,
    "version": 394496
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("minimal")
qt.core.plugin.factoryloader: looking at "/home/ubuntu/git/usdb_syncer/venv/lib/python3.11/site-packages/PySide6/Qt/plugins/platforms/libqlinuxfb.so"
qt.core.plugin.loader: Found metadata in lib /home/ubuntu/git/usdb_syncer/venv/lib/python3.11/site-packages/PySide6/Qt/plugins/platforms/libqlinuxfb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "linuxfb"
        ]
    },
    "archlevel": 1,
    "className": "QLinuxFbIntegrationPlugin",
    "debug": false,
    "version": 394496
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("linuxfb")
qt.core.plugin.factoryloader: looking at "/home/ubuntu/git/usdb_syncer/venv/lib/python3.11/site-packages/PySide6/Qt/plugins/platforms/libqeglfs.so"
qt.core.plugin.loader: Found metadata in lib /home/ubuntu/git/usdb_syncer/venv/lib/python3.11/site-packages/PySide6/Qt/plugins/platforms/libqeglfs.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "eglfs"
        ]
    },
    "archlevel": 1,
    "className": "QEglFSIntegrationPlugin",
    "debug": false,
    "version": 394496
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("eglfs")
qt.core.plugin.factoryloader: checking directory path "/usr/bin/platforms" ...
qt.core.library: "/home/ubuntu/git/usdb_syncer/venv/lib/python3.11/site-packages/PySide6/Qt/plugins/platforms/libqxcb.so" cannot load: Cannot load library /home/ubuntu/git/usdb_syncer/venv/lib/python3.11/site-packages/PySide6/Qt/plugins/platforms/libqxcb.so: (libxcb-cursor.so.0: cannot open shared object file: No such file or directory)
qt.core.plugin.loader: QLibraryPrivate::loadPlugin failed on "/home/ubuntu/git/usdb_syncer/venv/lib/python3.11/site-packages/PySide6/Qt/plugins/platforms/libqxcb.so" : "Cannot load library /home/ubuntu/git/usdb_syncer/venv/lib/python3.11/site-packages/PySide6/Qt/plugins/platforms/libqxcb.so: (libxcb-cursor.so.0: cannot open shared object file: No such file or directory)"
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, wayland, wayland-egl, vnc, vkkhrdisplay, offscreen, minimalegl, minimal, linuxfb, eglfs.

Aborted (core dumped)
```

**Comment by mjhalwa** [comment]
Installing following packages due to recommendations at https://stackoverflow.com/questions/68036484/qt6-qt-qpa-plugin-could-not-load-the-qt-platform-plugin-xcb-in-even-thou/72326758#72326758

```
sudo apt install libxcb-xinerama0
sudo apt install libxcb-cursor0
```

has different effects on execution of the clone and the release:

## Release

still has an error with some missing package

```
QT_DEBUG_PLUGINS="1" ./USDB_Syncer-0.1.0-Linux
```

turns into the following error

```
#....
qt.core.plugin.factoryloader: Got keys from plugin meta data QList("eglfs")
qt.core.plugin.factoryloader: checking directory path "/home/ubuntu/Downloads/platforms" ...
qt.core.library: "/tmp/_MEIeniTT4/PySide6/Qt/plugins/platforms/libqxcb.so" cannot load: Cannot load library /tmp/_MEIeniTT4/PySide6/Qt/plugins/platforms/libqxcb.so: (libQt6XcbQpa.so.6: cannot open shared object file: No such file or directory)
qt.core.plugin.loader: QLibraryPrivate::loadPlugin failed on "/tmp/_MEIeniTT4/PySide6/Qt/plugins/platforms/libqxcb.so" : "Cannot load library /tmp/_MEIeniTT4/PySide6/Qt/plugins/platforms/libqxcb.so: (libQt6XcbQpa.so.6: cannot open shared object file: No such file or directory)"
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, wayland, wayland-egl, vnc, vkkhrdisplay, offscreen, minimalegl, minimal, linuxfb, eglfs.

Aborted (core dumped)
```

## clone

seems to have no more missing packages but 

```
usdb_syncer
```

now runs into

```
qt.dbus.integration: Could not connect "org.freedesktop.IBus" to globalEngineChanged(QString)
2023-05-21 22:20:17 [ERROR] Uncaught exception:
    Traceback (most recent call last):
      File "/home/ubuntu/git/usdb_syncer/venv/bin/usdb_syncer", line 8, in <module>
    sys.exit(cli_entry())
             ^^^^^^^^^^^
      File "/home/ubuntu/git/usdb_syncer/src/usdb_syncer/main.py", line 31, in cli_entry
    main()
      File "/home/ubuntu/git/usdb_syncer/src/usdb_syncer/gui/mw.py", line 309, in main
    _load_main_window(mw)
      File "/home/ubuntu/git/usdb_syncer/src/usdb_syncer/gui/mw.py", line 318, in _load_main_window
    songs = get_all_song_data(False)
            ^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/git/usdb_syncer/src/usdb_syncer/song_list_fetcher.py", line 23, in get_all_song_data
    songs = get_available_songs(force_reload)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/git/usdb_syncer/src/usdb_syncer/song_list_fetcher.py", line 49, in get_available_songs
    songs += get_usdb_available_songs(max_skip_id, session=session)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/git/usdb_syncer/src/usdb_syncer/usdb_scraper.py", line 333, in get_usdb_available_songs
    html = get_usdb_page(
           ^^^^^^^^^^^^^^
      File "/home/ubuntu/git/usdb_syncer/src/usdb_syncer/usdb_scraper.py", line 231, in get_usdb_page
    return page()
           ^^^^^^
      File "/home/ubuntu/git/usdb_syncer/src/usdb_syncer/usdb_scraper.py", line 222, in page
    session or SessionManager.session(),
               ^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/git/usdb_syncer/src/usdb_syncer/usdb_scraper.py", line 78, in session
    cls._session = new_session_with_cookies(settings.get_browser())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/git/usdb_syncer/src/usdb_syncer/usdb_scraper.py", line 64, in new_session_with_cookies
    if cookies := browser.cookies():
                  ^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/git/usdb_syncer/src/usdb_syncer/settings.py", line 224, in cookies
    return function(domain_name=Usdb.DOMAIN)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/git/usdb_syncer/venv/lib/python3.11/site-packages/browser_cookie3/__init__.py", line 1028, in chrome
    return Chrome(cookie_file, domain_name, key_file).load()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/git/usdb_syncer/venv/lib/python3.11/site-packages/browser_cookie3/__init__.py", line 572, in __init__
    super().__init__(browser='Chrome', cookie_file=cookie_file, domain_name=domain_name, key_file=key_file, **args)
      File "/home/ubuntu/git/usdb_syncer/venv/lib/python3.11/site-packages/browser_cookie3/__init__.py", line 381, in __init__
    self.__add_key_and_cookie_file(**kwargs)
      File "/home/ubuntu/git/usdb_syncer/venv/lib/python3.11/site-packages/browser_cookie3/__init__.py", line 394, in __add_key_and_cookie_file
    password = _LinuxPasswordManager(USE_DBUS_LINUX).get_password(os_crypt_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/git/usdb_syncer/venv/lib/python3.11/site-packages/browser_cookie3/__init__.py", line 226, in get_password
    return self.__methods_map.get('kwallet')(os_crypt_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    TypeError: _LinuxPasswordManager.__get_kdewallet_password_jeepney() missing 1 required positional argument: 'key'
```

which looks like #136

It's quite late now, I give up for today, but try to follow up in the next days.

**Comment by mjhalwa** [comment]
There is an interesting statement at https://github.com/Nuitka/Nuitka/issues/2138#issuecomment-1486292343

> For Linux you need to **build on older Linux**, definitely **not latest** Linux, or else due to libc, things cannot be loaded.

**Comment by mjhalwa** [comment]
Tried following installs (to resolve the missing packages in the Release):

suggested by https://packages.ubuntu.com/lunar/libxcb-util0-dev:

```
sudo apt install libxcb-util-dev
```

suggested by https://github.com/Nuitka/Nuitka/issues/2138

```
sudo apt install -y \
            libfontconfig1-dev libfreetype6-dev \
            libx11-dev libx11-xcb-dev libxext-dev libxfixes-dev \
            libxi-dev libxrender-dev \
            libxkbcommon-dev libxkbcommon-x11-dev libatspi2.0-dev \
            libopengl0 '^libxcb.*-dev'
```

and suggested by https://stackoverflow.com/questions/68036484/qt6-qt-qpa-plugin-could-not-load-the-qt-platform-plugin-xcb-in-even-thou

```
sudo apt-get install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev
```

**BUT** the last Debug output with `libQt6XcbQpa.so.6: cannot open shared object file: No such file or directory` did not change

Then following https://stackoverflow.com/a/74719383 I tried

```
export QT_QPA_PLATFORM=offscreen
```

which turned the output of `./USDB_Syncer-0.1.0-Linux` into

```
qt.dbus.integration: Could not connect "org.freedesktop.IBus" to globalEngineChanged(QString)
2023-05-22 20:20:28 [ERROR] Uncaught exception:
    Traceback (most recent call last):
      File "usdb_syncer/main.py", line 36, in <module>
      File "usdb_syncer/main.py", line 31, in cli_entry
      File "usdb_syncer/gui/mw.py", line 309, in main
      File "usdb_syncer/gui/mw.py", line 318, in _load_main_window
      File "usdb_syncer/song_list_fetcher.py", line 23, in get_all_song_data
      File "usdb_syncer/song_list_fetcher.py", line 49, in get_available_songs
      File "usdb_syncer/usdb_scraper.py", line 333, in get_usdb_available_songs
      File "usdb_syncer/usdb_scraper.py", line 231, in get_usdb_page
      File "usdb_syncer/usdb_scraper.py", line 222, in page
      File "usdb_syncer/usdb_scraper.py", line 78, in session
      File "usdb_syncer/usdb_scraper.py", line 64, in new_session_with_cookies
      File "usdb_syncer/settings.py", line 224, in cookies
      File "browser_cookie3/__init__.py", line 973, in chrome
      File "browser_cookie3/__init__.py", line 516, in __init__
      File "browser_cookie3/__init__.py", line 331, in __init__
      File "browser_cookie3/__init__.py", line 344, in __add_key_and_cookie_file
      File "browser_cookie3/__init__.py", line 238, in get_password
    TypeError: _LinuxPasswordManager.__get_kdewallet_password_jeepney() missing 1 required positional argument: 'key'
[12852] Failed to execute script 'main' due to unhandled exception!
```

which now looks pretty much identical to #136 

while the Output of the clone remained unchanged

**Comment by mjhalwa** [comment]
After looking up some things I tried bundeling and installing some dependencies. I created several Release on my fork in order to test different combinations.

On a fresh Ubuntu 23.04 the Release [0.1.10010](https://github.com/mjhalwa/usdb_syncer/releases/tag/0.1.10010) worked well. I just had to

```
sudo apt update && sudo apt upgrade
sudo apt install ffmpeg
```

If 0.1.10010 does not work for you, please tell me if any of the following versions at https://github.com/mjhalwa/usdb_syncer/releases work for you (each version installs more dependencies upon the dependencies of the version before)

Note: the Build-step of the release workflow for Linux still shows these warnings, so i tried some more installs in 0.1.10014

```
2617 WARNING: Cannot find libwebp-8b6d8948.so.7.1.7 (needed by /opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/PIL/../Pillow.libs/libwebpdemux-fc93391d.so.2.0.13)
2625 WARNING: Cannot find libsharpyuv-20f78091.so.0.0.1 (needed by /opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/PIL/../Pillow.libs/libwebp-8b6d8948.so.7.1.7)
2640 WARNING: Cannot find libwebp-8b6d8948.so.7.1.7 (needed by /opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/PIL/../Pillow.libs/libwebpmux-b3bcb8ec.so.3.0.12)
2663 WARNING: Cannot find liblzma-9dd5c569.so.5.4.3 (needed by /opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/PIL/../Pillow.libs/libtiff-189042a3.so.6.0.1)
2663 WARNING: Cannot find libjpeg-dab02bf4.so.62.3.0 (needed by /opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/PIL/../Pillow.libs/libtiff-189042a3.so.6.0.1)
2686 WARNING: Cannot find libXau-154567c4.so.6.0.0 (needed by /opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/PIL/../Pillow.libs/libxcb-cd9c1006.so.1.1.0)
```

If 0.1.10010 works for you, I would try another version with just installing libxcb-cursor0 without bundeling platforms directory or try to add not the whole platforms directory
