### ISSUE TITLE
Pdf generation broken

### ISSUE THREAD

**Issue by fahrnertim** [bohning/usdb_syncer#195]
On Version 0.3.0 when trying to export my songlist to a pdf the following exception is thrown:
2023-11-10 11:23:20 [ERROR] Uncaught exception:
    Traceback (most recent call last):
      File "usdb_syncer\gui\mw.py", line 324, in _generate_song_pdf
      File "usdb_syncer\pdf.py", line 36, in generate_song_pdf
      File "pdfme\document.py", line 496, in build_pdf
      File "pdfme\document.py", line 288, in run
      File "pdfme\document.py", line 357, in _process_section
      File "pdfme\document.py", line 376, in _add_content
      File "pdfme\content.py", line 254, in run
      File "pdfme\content.py", line 578, in run
      File "pdfme\content.py", line 508, in add_elements
      File "pdfme\content.py", line 817, in process
      File "pdfme\content.py", line 866, in process_text
      File "pdfme\text.py", line 651, in run
      File "pdfme\text.py", line 704, in add_part
      File "pdfme\text.py", line 344, in add_word
      File "pdfme\text.py", line 115, in add_word
      File "pdfme\text.py", line 167, in get_word_width
      File "pdfme\fonts.py", line 134, in get_text_width
      File "pdfme\fonts.py", line 134, in <genexpr>
    KeyError: '…'

Not sure what further Information to provide.
Just ask and I ll try to answer.

**Comment by bohning** [comment]
This is a problem of the pdfme module. Apparently, it can’t handle the ellipsis (…) character. Please report it upstream: [https://github.com/pdfme/pdfme/issues](https://github.com/pdfme/pdfme/issues)

**Comment by mjhalwa** [comment]
@fahrnertim did you try the new JSON Export feature? I wonder if the JSON export might also fulfill your usecase or if you would still prefer a JSON export. The idea was that the JSON export would support a wider range of custom visualizations.

**Comment by Baklap4** [comment]
I took a look at the pdf generation, this is still the case, but pdfme -> https://github.com/aFelipeSP/pdfme hasn't been updated since quite some time

**Comment by bohning** [comment]
There's a [branch](https://github.com/bohning/usdb_syncer/tree/fix_pdf) that migrates to reportlab, but the open issue is font support. A huge set of fonts (e.g. Noto) would be needed to support all different script present in usdb (including some CJK).

**Comment by bohning** [comment]
Fixed with #383 .
