### ISSUE TITLE
Version 0.5 crashes

### ISSUE THREAD

**Issue by stb2015** [bohning/usdb_syncer#237]
Version 0.5 crashes with the following error:

Arguments: ()
2024-03-07 10:58:24 [INFO] New meta file found on disk: 'H:\usdb\★N Sync feat. Lisa “Left Eye” Lopes - Space Cowboy (Yippie-Yi-Yay)\-6owAozUBus.usdb'.
2024-03-07 10:58:25 [ERROR] Uncaught exception:
    Traceback (most recent call last):
      File "usdb_syncer\gui\__init__.py", line 167, in <module>
      File "usdb_syncer\gui\__init__.py", line 41, in main
      File "usdb_syncer\gui\__init__.py", line 51, in _run
      File "usdb_syncer\gui\__init__.py", line 84, in _load_main_window
      File "usdb_syncer\song_routines.py", line 74, in synchronize_sync_meta_folder
      File "usdb_syncer\sync_meta.py", line 181, in upsert_many
      File "usdb_syncer\db\__init__.py", line 478, in delete_resource_files
    sqlite3.OperationalError: too many SQL variables
[22880] Failed to execute script '__init__' due to unhandled exception!

Version 0.4 works.

Song Database is complete: 26441 songs

**Comment by stb2015** [comment]
Did not use dev-build. Started with version 0.3.

Deleted usdb_syncer.db. Did not change still crashing with version 0.5. Might be path or filename problem:
--- Logging error ---
Traceback (most recent call last):
  File "logging\__init__.py", line 1113, in emit
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u2605' in position 65: character maps to <undefined>
Call stack:
  File "usdb_syncer\gui\__init__.py", line 167, in <module>
  File "usdb_syncer\gui\__init__.py", line 41, in main
  File "usdb_syncer\gui\__init__.py", line 51, in _run
  File "usdb_syncer\gui\__init__.py", line 84, in _load_main_window
  File "usdb_syncer\song_routines.py", line 72, in synchronize_sync_meta_folder
  File "logging\__init__.py", line 1489, in info
  File "logging\__init__.py", line 1634, in _log
  File "logging\__init__.py", line 1644, in handle
  File "logging\__init__.py", line 1706, in callHandlers
  File "logging\__init__.py", line 978, in handle
  File "logging\__init__.py", line 1230, in emit
  File "logging\__init__.py", line 1118, in emit
Message: "New meta file found on disk: 'H:\\usdb\\★N Sync feat. Lisa “Left Eye” Lopes - Space Cowboy (Yippie-Yi-Yay)\\-6owAozUBus.usdb'."
Arguments: ()
2024-03-10 18:21:23 [INFO] New meta file found on disk: 'H:\usdb\★N Sync feat. Lisa “Left Eye” Lopes - Space Cowboy (Yippie-Yi-Yay)\-6owAozUBus.usdb'.
2024-03-10 18:21:24 [ERROR] Uncaught exception:
    Traceback (most recent call last):
      File "usdb_syncer\gui\__init__.py", line 167, in <module>
      File "usdb_syncer\gui\__init__.py", line 41, in main
      File "usdb_syncer\gui\__init__.py", line 51, in _run
      File "usdb_syncer\gui\__init__.py", line 84, in _load_main_window
      File "usdb_syncer\song_routines.py", line 74, in synchronize_sync_meta_folder
      File "usdb_syncer\sync_meta.py", line 181, in upsert_many
      File "usdb_syncer\db\__init__.py", line 478, in delete_resource_files
    sqlite3.OperationalError: too many SQL variables
[12820] Failed to execute script '__init__' due to unhandled exception!

**Comment by RumovZ** [comment]
Thanks for the report. Should be fixed in the next release.
The Unicode error wasn't related, but is also fixed now.
