### ISSUE TITLE
Endless "Reading meta files ..." when switching song folder

### ISSUE THREAD

**Issue by rakuri255** [bohning/usdb_syncer#252]
Switching the song folder to a new folder with some song in it, brings the syncer into endless "Reading meta files ..."
In my case there are 5 songs in the new folder.

**Comment by RumovZ** [comment]
What version are you running?

I assume there's a hidden error in the background task. With #254, it should be properly propogated, which should tell us what the underlying issue is.

**Comment by rakuri255** [comment]
@RumovZ i use the released 0.5.0 version

**Comment by rakuri255** [comment]
```
2024-07-01 19:34:38 [ERROR] Uncaught exception:
    Traceback (most recent call last):
      File "F:\Games\UltraStar\archiv\usdb_syncer\src\usdb_syncer\gui\mw.py", line 170, in _select_song_dir
    run_with_progress(
      File "F:\Games\UltraStar\archiv\usdb_syncer\src\usdb_syncer\gui\progress.py", line 42, in run_with_progress
    raise cast(Exception, exception)  # pylint: disable=raising-bad-type
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "F:\Games\UltraStar\archiv\usdb_syncer\src\usdb_syncer\gui\progress.py", line 32, in wrapped_task
    out = task(dialog)
          ^^^^^^^^^^^^
      File "F:\Games\UltraStar\archiv\usdb_syncer\src\usdb_syncer\gui\mw.py", line 172, in <lambda>
    lambda _: song_routines.synchronize_sync_meta_folder(path),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "F:\Games\UltraStar\archiv\usdb_syncer\src\usdb_syncer\song_routines.py", line 101, in synchronize_sync_meta_folder
    SyncMeta.upsert_many(to_upsert)
      File "F:\Games\UltraStar\archiv\usdb_syncer\src\usdb_syncer\sync_meta.py", line 175, in upsert_many
    db.upsert_resource_files(
      File "F:\Games\UltraStar\archiv\usdb_syncer\src\usdb_syncer\db\__init__.py", line 573, in upsert_resource_files
    _DbState.connection().executemany(stmt, (p.__dict__ for p in params))
    sqlite3.IntegrityError: NOT NULL constraint failed: resource_file.resource
```

**Comment by RumovZ** [comment]
Thanks!
I think we had a similar report before. An early version of the Syncer didn't enforce a resource name.
How do you go with [2ed328d](https://github.com/bohning/usdb_syncer/pull/256/commits/2ed328d09d4f10f8f63e2d7f136cea589bffdc15)?

**Comment by rakuri255** [comment]
yes that solves the problem
