### ISSUE TITLE
poetry run usdb_syncer fails with ImportError: libpulse.so.0

### ISSUE THREAD

**Issue by derhasi** [bohning/usdb_syncer#303]
After having trouble installing the project but hopefully resolving that (see #302), I know run into an error, starting up the project with `poetry run usdb_syncer`. 

I'm running Ubuntu 24.04.1 LTS (Noble Numbat) in Windows 10 WSL.

```
(usdb-syncer-py3.12) derhasi@DESKTOP-AOC7TBL:~/code/usdb_syncer$ poetry run usdb_syncer
ERROR:root:Uncaught exception:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/derhasi/code/usdb_syncer/src/usdb_syncer/gui/__init__.py", line 52, in main
    _run()
      File "/home/derhasi/code/usdb_syncer/src/usdb_syncer/gui/__init__.py", line 56, in _run
    from usdb_syncer.gui.mw import MainWindow  # pylint: disable=import-outside-toplevel
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/derhasi/code/usdb_syncer/src/usdb_syncer/gui/mw.py", line 22, in <module>
    from usdb_syncer.gui.song_table.song_table import SongTable
      File "/home/derhasi/code/usdb_syncer/src/usdb_syncer/gui/song_table/song_table.py", line 10, in <module>
    from PySide6 import QtCore, QtGui, QtMultimedia, QtWidgets
    ImportError: libpulse.so.0: cannot open shared object file: No such file or directory
```

**Comment by RumovZ** [comment]
Works on WSL for me, but apparently there are libs missing on yours, like libpulse. Here's the list which gets installed for Qt in our CI: https://github.com/jurplel/install-qt-action/blob/master/action/src/main.ts#L317-L343
